ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS age integer;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS weight numeric;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS height numeric;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS bmi numeric;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS body_type text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS archetype text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS personality_traits text[];
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS life_balance jsonb;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS habits_completed integer DEFAULT 0;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS current_streak integer DEFAULT 0;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS improvement_rate text;
